package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF2F6FED)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE7FD)
val LightOnPrimaryContainer = Color(0xFF153778)
val LightSecondary = Color(0xFF667085)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFEDEFF5)
val LightOnSecondaryContainer = Color(0xFF344054)
val LightTertiary = Color(0xFFF3B4C1)
val LightOnTertiary = Color(0xFF5A2430)
val LightBackground = Color(0xFFF4F6F9)
val LightOnBackground = Color(0xFF1F2937)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1F2937)
val LightSurfaceVariant = Color(0xFFF8FAFC)
val LightOnSurfaceVariant = Color(0xFF667085)
val LightOutline = Color(0xFFD8E0EA)
val LightError = Color(0xFFDC4C64)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFE1E8)
val LightOnErrorContainer = Color(0xFF681626)

val DarkPrimary = Color(0xFF6F98D8)
val DarkOnPrimary = Color(0xFF0E213F)
val DarkPrimaryContainer = Color(0xFF1B2B40)
val DarkOnPrimaryContainer = Color(0xFFD9E6FB)
val DarkSecondary = Color(0xFF93A6BA)
val DarkOnSecondary = Color(0xFF14202C)
val DarkSecondaryContainer = Color(0xFF182534)
val DarkOnSecondaryContainer = Color(0xFFD9E3EE)
val DarkTertiary = Color(0xFFBFD4FF)
val DarkOnTertiary = Color(0xFF1A2940)
val DarkBackground = Color(0xFF0A1118)
val DarkOnBackground = Color(0xFFE7EEF6)
val DarkSurface = Color(0xFF0F1822)
val DarkOnSurface = Color(0xFFE7EEF6)
val DarkSurfaceVariant = Color(0xFF131E2A)
val DarkOnSurfaceVariant = Color(0xFF93A6BA)
val DarkOutline = Color(0xFF1F2B38)
val DarkError = Color(0xFFFF7389)
val DarkOnError = Color(0xFF4F0D1B)
val DarkErrorContainer = Color(0xFF682031)
val DarkOnErrorContainer = Color(0xFFFFD9E0)
